server:
  port: 3030

#FakeStore config variables.
fakestore:
  api:
    url: https://fakestoreapi.com
    path:
      products: /products
      categories: /categories

#DB Connection
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productservice
    username: productuser
    #password: welcome1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true